(()=>{
const esc=window.FLIPCO?.esc||((s)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])));
const fallback=p=>p?.art?`assets/products/${esc(p.art)}`:''; const src=p=>p?.image||fallback(p);
const img=(p,alt='')=>`<img src="${esc(src(p))}" alt="${esc(alt||`${p?.brand||''} ${p?.name||''}`)}" loading="lazy" decoding="async" onerror="this.onerror=null;this.src='${fallback(p)}'>`;
const live=p=>{try{return FLIPCO.stock(p)>0}catch{return !!p.available}};
async function boot(){let products=[];try{products=await FLIPCO.load()}catch{}if(!products.length)return;const available=products.filter(live),by=id=>products.find(p=>p.id===id);
const grid=document.querySelector('#fxEditGrid'),count=document.querySelector('#fxEditCount');let filter='all';
const filtered=()=>available.filter(p=>filter==='all'||String(p.category).toLowerCase()===filter.toLowerCase()||String(p.type).toLowerCase()===filter.toLowerCase());
const card=(p,i)=>`<a class="fx-product-card ${i%4===1?'fx-offset':''}" href="product.html?id=${encodeURIComponent(p.id)}"><div class="fx-product-image">${img(p)}</div><div class="fx-product-meta"><small>${esc(p.brand)} · ${esc(p.category)}</small><b>${esc(p.name)}</b><span>${FLIPCO.money(p.price)}</span><div class="fx-product-status">${esc(p.badge||'ONLINE EDIT')}</div></div></a>`;
const render=()=>{const arr=filtered();if(grid)grid.innerHTML=arr.length?arr.map(card).join(''):`<div class="fx-empty"><span>NO EXACT MATCH</span><b>Nessun match esatto nell’Online Edit.</b><a class="fx-link" target="_blank" rel="noopener" href="https://wa.me/393661087819?text=Ciao%20Flip%26Co%2C%20non%20trovo%20quello%20che%20cerco%20e%20vorrei%20un%20consiglio.">CHIEDI AL TEAM ↗</a></div>`;if(count)count.textContent=`${String(arr.length).padStart(2,'0')} PIECES / CURATED`};
render();document.querySelectorAll('.fx-filter-strip button').forEach(b=>b.addEventListener('click',()=>{filter=b.dataset.filter||'all';document.querySelectorAll('.fx-filter-strip button').forEach(x=>x.classList.toggle('active',x===b));render()}));
const stories=document.querySelector('#fxStories');if(stories){const ids=['FLI-GCDS-BAND-MAN','FLI-PINKO-LOVE-BAG','DSQ2-PUFF-KIDS','NB9060-ERC'];const ss=ids.map(by).filter(p=>p&&live(p));stories.innerHTML=ss.map((p,i)=>`<article class="fx-story ${i%2?'fx-story-reverse':''}"><div class="fx-story-media">${img(p)}</div><div class="fx-story-info"><small>${esc(p.brand)} · ${esc(p.category)} · ${esc(p.type||'')}</small><h2>${esc(p.name.split(' ').slice(0,-1).join(' ')||p.name)}<br><em>${esc(p.name.split(' ').slice(-1)[0])}.</em></h2><p>${esc(p.description||'Una selezione Flip&Co scelta per l’Online Edit.')}</p><strong>${FLIPCO.money(p.price)}</strong><div class="fx-story-actions"><a class="fx-link" href="product.html?id=${encodeURIComponent(p.id)}">VEDI IL PRODOTTO ↗</a></div></div></article>`).join('')}
const state={audience:null,need:null},result=document.querySelector('#finderResult'),search=document.querySelector('#finderSearch');
const find=()=>available.filter(p=>{if(!state.audience||!state.need)return false;const a=String(p.category).toLowerCase();if(a!==state.audience.toLowerCase())return false;return state.need==='all'||String(p.type).toLowerCase()===state.need});
const status=()=>{if(!result||!search)return;const n=Number(!!state.audience)+Number(!!state.need);search.disabled=n!==2;result.querySelector('span').textContent=`${n}/2 RISPOSTE SELEZIONATE`;result.querySelector('b').textContent=n===2?'Perfetto. La tua selezione è pronta.':n===1?'Perfetto. Completa la seconda scelta.':'Dimmi per chi stai cercando e cosa ti serve.'};
document.querySelectorAll('[data-finder] button').forEach(b=>b.addEventListener('click',()=>{const g=b.closest('[data-finder]').dataset.finder;state[g]=b.dataset.value;b.parentElement.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));status()}));
search?.addEventListener('click',()=>{const arr=find();if(grid){grid.innerHTML=arr.length?arr.map(card).join(''):`<div class="fx-empty"><span>ONLINE EDIT</span><b>Non trovo un match esatto online. Il negozio può avere altre opzioni.</b><a class="fx-link" target="_blank" rel="noopener" href="https://wa.me/393661087819?text=Ciao%20Flip%26Co%2C%20sto%20cercando%20qualcosa%20di%20specifico.%20Mi%20aiutate%3F">PARLA CON IL TEAM ↗</a></div>`;if(count)count.textContent=`${String(arr.length).padStart(2,'0')} PIECES / YOUR EDIT`}document.querySelector('#edit')?.scrollIntoView({behavior:'smooth',block:'start'})});status();}
boot();})();
